# Prevents duplicate builds from occurring after Travis updates the tag in GitHub
if: tag IS blank

language: java
jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2"

## export GPG details
before_install:
  - $GPG_EXECUTABLE --version
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

script:
  - mvn clean package archetype:integration-test --settings .maven.xml --batch-mode  -U deploy -Prelease

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
  - export TRAVIS_TAG=$project_version

deploy:
  provider: releases
  api_key:
    secure: "KafR7Ej7l+ms4MTbNP0RnNYXVjttUwBSwdI4ezHsg2Tgmi1jCDo3Lzc75jsNJZme7OyVFSqQDoimNED8DoGF6VgUlAgWbfkRR/OgbE+5JRfd3AlvYtrZvO+6/xvornfBeRbMyoxetbFaSp/77msFuXTJrH/Bm5vMH0S0d27rHYMpy7B72iOkpptewlcSwJNsW5TKVY/aOTO5X6wSJ33/D5Z6PYdqDJN3RvdK8FUBXUjyglj4FUlfhfGObh4nWzDjyIi/ZnI0/COi80OZ8ANB4n5XaFsdQnlR2YN01cVw8bpRxXE7Y52IiHE4rkTuB7cOKDQkrOrmKRiIxJSGgItIUUXM3JxN4n6wCxSnF9LWjDAy3hted1WPy7+cxWmnO+lOg+80IDm08hQtCRgPkQpYAzvgooKL1T8/12MtLleKBjWWdOFUA7rl40Lfai5+u719c9YfldYFxMK1/XESf4uqflFcWrvz+/L06syiarduA2orqvfcI5kw/VVX5pn7TjfVJucNiE4TZKM96XvUW/Ytj+Jn63Jb9SmbgLUiQeQ/UJtJUfB/QDq+kE2Fa9FAw22F8H9JhI6EvlRg1w7qk1Y3wWyXnI3gaSdf+eqfYsNExfEtNYOhmAocAJ7K8xLgy+PPS6QkZejIzxSu4yXMsTbKYnAD2YB0iIoaqV7SJH6tQbU="
  file: target/nexus-format-archetype-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    tags: true
## figure out if we can increment maven SNAPSHOT versions here (e.g. via maven-release-plugin) -requires ability to do github push, etc
#    - mvn release:prepare --settings .maven.xml --batch-mode -V -Prelease -Darguments="--settings .maven.xml"
#    - mvn release:perform --settings .maven.xml --batch-mode -V -Prelease -Darguments="--settings .maven.xml"
